[env:esp32-2424S012C]
platform = espressif32
board = esp32-2424S012C
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv

lib_deps =
    lvgl/lvgl@^8.3.9
    lovyan03/LovyanGFX@^1.1.12
    fbiego/CST816S@^1.1.1
    bblanchon/ArduinoJson@^6.21.3

build_flags =
    -D LV_CONF_SKIP=1
    -D LV_COLOR_DEPTH=16
    -D LV_COLOR_16_SWAP=1
    -D LV_MEM_SIZE=32768
    -D LV_FONT_MONTSERRAT_24=1
    -D LV_FONT_MONTSERRAT_32=1
    -D LV_FONT_MONTSERRAT_48=1
    -I include
    -I src
